Integrate LoRA into the codebase
PygmalionAI/accelerate-training-code pull request #6
Opened 2023-03-09 00:02 UTC by TearGosling

LoRA promises significant reductions in memory. Hopefully, it will help take us to higher-scale models such as 12B and 20B. Right now, this is fine as is, but with the one caveat that I'm not exactly sure how to have it such that the LoRA weights are properly merged with the model. `merge_weights=True` in the `LoraConfig` doesn't do the trick, it seems. I'll be looking into it further, but in the meantime, this should be good to at least test out LoRA's effects on VRAM usage.

2023-03-09 00:21 UTC, 0x000011b reviewed
Thanks, mostly LGTM! Left a few minor comments but nothing that blocks usage, will be testing before merging.

2023-03-09 00:21 UTC, 0x000011b commented on src/training/sft.py
> +        rewards = torch.ones((self.args.batch_size, 1)).to("cuda")
Not important for this case since it's a single warmup step, but just for future reference:

The [PyTorch documentation](https://pytorch.org/tutorials/recipes/recipes/tuning_guide.html#create-tensors-directly-on-the-target-device) recommends that tensors be created directly on the target device by passing in `device="whatever"` instead of creating in the CPU and then moving to the target device.

2023-03-09 00:21 UTC, 0x000011b commented on src/training/sft.py
> +            # max_position_embeddings = 2048
Do we need this for something?

2023-03-09 03:44 UTC, TearGosling commented on src/training/sft.py
> +        rewards = torch.ones((self.args.batch_size, 1)).to("cuda")
Ah, right. Forgot about that. I can quickly fix that.

2023-03-09 03:49 UTC, TearGosling commented on src/training/sft.py
> +            # max_position_embeddings = 2048
The [PyTorch tips](https://pytorch.org/tutorials/recipes/recipes/tuning_guide.html#pre-allocate-memory-in-case-of-variable-input-length) say that the fake batch that should be created preferably with randomly generated batches as inputs. `torch.randint()` in this case would make a tensor that resembles a "random" batch of tokenized text, in our case with the maximum sequence length. You could argue that I should do this for say, the starting and ending positions, but it might be more trouble than it's worth at that point.

2023-03-11 00:33 UTC, 0x000011b commented on src/training/sft.py
> +            # max_position_embeddings = 2048
Yep, I meant the commented out `# max_position_embeddings = 2048`. Will we need that eventually? Or was it supposed to be un-commented/removed entirely?

2023-03-11 00:35 UTC, 0x000011b requested changes
Got the chance to test the code and found some minor issues, but after fixing these it's good to merge.

2023-03-11 00:35 UTC, 0x000011b commented on src/training/sft.py
> +            cringe_loss=self.args.use_cringe_loss
These don't exist on `main`, so running this branch as-is doesn't work.

2023-03-11 00:35 UTC, 0x000011b commented on src/training/sft.py
> +        model_config = self.model.gpt_neox.config
Needs to be:

```suggestion
        model_config = self.model.module.gpt_neox.config
```

Because of DeepSpeed.

2023-03-11 00:35 UTC, 0x000011b commented on src/training/sft.py
> +        )
Makes sense. For now, can we get just `r` converted into a CLI argument? I think it's the most important one we should be trying to tune - we can add in alpha and dropout later if relevant.

2023-03-11 01:34 UTC, 0x000011b approved these changes
Awesome, LGTM now. Thanks.

2023-03-11 01:34 UTC, merged